#!/bin/sh
# ip link set $IFNAME address $MAC mtu $MTU up
ip link set $IFNAME mtu $MTU up

[ $NODENAME = dl  ] &&     ip -6 addr add FEC0::1/120 dev $IFNAME
[ $NODENAME = bj ] &&      ip -6 addr add FEC0::2/120 dev $IFNAME
[ $NODENAME = yinzh ] &&   ip -6 addr add FEC0::3/120 dev $IFNAME
[ $NODENAME = vps ] &&     ip -6 addr add FEC0::4/120 dev $IFNAME
[ $NODENAME = asus ] &&    ip -6 addr add FEC0::5/120 dev $IFNAME
[ $NODENAME = gvpe-bj ] && ip -6 addr add FEC0::6/120 dev $IFNAME
ip -6 route add FEC0::0/120 dev $IFNAME
# iptables -t nat -A POSTROUTING -j MASQUERADE
# iptables -t nat -D POSTROUTING -s 10.0.1.0/24 -j MASQUERADE
# iptables -t nat -A POSTROUTING -s 10.0.1.0/24 -j MASQUERADE

# Creating tun device.
# ip tuntap del $IFNAME mode tun
# ip tuntap add $IFNAME mode tun
